/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Control_Panel.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_TEXT_0             (GUI_ID_USER + 0x01)
#define ID_TEXT_1             (GUI_ID_USER + 0x02)
#define ID_TEXT_2             (GUI_ID_USER + 0x03)
#define ID_TEXT_3             (GUI_ID_USER + 0x04)
#define ID_TEXT_4             (GUI_ID_USER + 0x05)
#define ID_TEXT_5             (GUI_ID_USER + 0x06)
#define ID_BUTTON_0             (GUI_ID_USER + 0x07)
#define ID_BUTTON_1             (GUI_ID_USER + 0x08)
#define ID_BUTTON_2             (GUI_ID_USER + 0x09)
#define ID_BUTTON_3             (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4             (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern SemaphoreHandle_t xMaWinFlag_ON;
extern SemaphoreHandle_t xMaWinFlag_OFF;
extern SemaphoreHandle_t xCtrlWinFlag_ON;
extern SemaphoreHandle_t xCtrlWinFlag_OFF;

extern TaskHandle_t Main_WinHandle;

uint8_t headlits=0,leftindic=0,rightindic=0,hazarlits=0;
uint8_t Light[]={0xA1,0xC2,0x32,0xF2,0x54};			//指令分别为前照灯、左转向灯、右转向灯、警示灯、行驶灯
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Control Panel", ID_WINDOW_0, 1, 1, 480, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Title", ID_TEXT_0, 15, 20, 200, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Headlights", ID_TEXT_1, 26, 80, 88, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Turn Indicators", ID_TEXT_2, 180, 80, 120, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Hazard Lights", ID_TEXT_3, 355, 80, 110, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Left Turn Indicators", ID_TEXT_4, 190, 110, 100, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Right Turn Indicators", ID_TEXT_5, 190, 200, 100, 16, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Return", ID_BUTTON_0, 320, 20, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Headlights", ID_BUTTON_1, 20, 130, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Left Turn Indicators", ID_BUTTON_2, 190, 130, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Right Turn Indicators", ID_BUTTON_3, 190, 220, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Hazard Lights", ID_BUTTON_4, 360, 130, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void CWin_PaintDialog(WM_MESSAGE * pMsg)
{
	WM_HWIN hWin = pMsg->hWin;
	hWin = hWin; //Useless, only to reference 'hWin'
	GUI_DrawGradientV(0,0,480,320,GUI_MAKE_COLOR(0x00C53858),GUI_DARKGREEN);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
	case WM_PAINT:
		CWin_PaintDialog(pMsg);
		break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Title'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Control Panel");
    //
    // Initialization of 'Headlights'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "Headlights");
    //
    // Initialization of 'Turn Indicators'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Turn Indicators");
    //
    // Initialization of 'Hazard Lights'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "Hazard Lights");
    //
    // Initialization of 'Left Turn Indicators'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "Left");
    //
    // Initialization of 'Right Turn Indicators'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "Right");
    //
    // Initialization of 'Return'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Return");
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Headlights'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    if(headlits)BUTTON_SetText(hItem, "ON");
		else BUTTON_SetText(hItem, "OFF");
    //
    // Initialization of 'Left Turn Indicators'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    if(leftindic)BUTTON_SetText(hItem, "ON");
		else BUTTON_SetText(hItem, "OFF");    //
    // Initialization of 'Right Turn Indicators'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    if(rightindic)BUTTON_SetText(hItem, "ON");
		else BUTTON_SetText(hItem, "OFF");    //
    // Initialization of 'Hazard Lights'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    if(hazarlits)BUTTON_SetText(hItem, "ON");
		else BUTTON_SetText(hItem, "OFF");    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				xSemaphoreGive(xMaWinFlag_ON);
				xSemaphoreGive(xCtrlWinFlag_OFF); 
				vTaskResume(Main_WinHandle);
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Headlights'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				if(headlits){can_tx(Light[0],OFF);	headlits=0;}
				else {can_tx(Light[0],ON);	headlits=1;}
        break;
      case WM_NOTIFICATION_RELEASED:
				if(headlits){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
				BUTTON_SetText(hItem, "ON");}
				else {
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
				BUTTON_SetText(hItem, "OFF");}
        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Left Turn Indicators'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				if(leftindic){can_tx(Light[1],OFF);	leftindic=0;}
				else {can_tx(Light[1],ON);	leftindic=1;}
        break;
      case WM_NOTIFICATION_RELEASED:
				if(leftindic){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				BUTTON_SetText(hItem, "ON");}
				else {
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				BUTTON_SetText(hItem, "OFF");}
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Right Turn Indicators'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				if(rightindic){can_tx(Light[2],OFF);	rightindic=0;}
				else {can_tx(Light[2],ON);	rightindic=1;}
        break;
      case WM_NOTIFICATION_RELEASED:
				if(rightindic){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				BUTTON_SetText(hItem, "ON");}
				else {
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				BUTTON_SetText(hItem, "OFF");}
        break;
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Hazard Lights'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				if(hazarlits){can_tx(Light[3],OFF);	hazarlits=0;}
				else {can_tx(Light[3],ON);	hazarlits=1;}
        break;
      case WM_NOTIFICATION_RELEASED:
				if(hazarlits){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				BUTTON_SetText(hItem, "ON");}
				else {
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				BUTTON_SetText(hItem, "OFF");}
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateControl Panel
*/
void Control_Panel(void *pvParameters);
void Control_Panel(void *pvParameters) 
{
  WM_HWIN hWin;
	uint8_t CtrlWin_Flag=0;
	
	WM_SetCreateFlags(WM_CF_MEMDEV);  						/* Use memory devices on all windows to avoid flicker */
	WM_SetDesktopColor(GUI_BLACK);      					/* Automacally update desktop window */
	
	while(1){
		if(xSemaphoreTake(xCtrlWinFlag_OFF,0) == pdPASS)
		{
			if(CtrlWin_Flag ==1)
			{
				CtrlWin_Flag = 0;
				GUI_EndDialog(WM_GetClientWindow(hWin), 0);
				vTaskSuspend(NULL);
			}
		}
		GUI_Delay(1);	
		if(xSemaphoreTake(xCtrlWinFlag_ON,0) == pdPASS)
		{
			if(CtrlWin_Flag ==0)
			{
				hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
				CtrlWin_Flag = 1;
			}
		}	
		GUI_Delay(1);
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
