/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Main_Window.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         (GUI_ID_USER + 0x00)
#define ID_BUTTON_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_1         (GUI_ID_USER + 0x02)
#define ID_BUTTON_2         (GUI_ID_USER + 0x03)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
void MWin_PaintDialog(WM_MESSAGE * pMsg);

extern TaskHandle_t Record_WinHandle;
//extern TaskHandle_t Details_WinHandle;
extern TaskHandle_t Control_WinHandle;

extern QueueHandle_t xCAN_V_TxMessage;
extern QueueHandle_t xTIM_T_TxMessage;

extern SemaphoreHandle_t xMaWinFlag_OFF;
extern SemaphoreHandle_t xMaWinFlag_ON;
extern SemaphoreHandle_t xRecWinFlag_ON;
extern SemaphoreHandle_t xRecWinFlag_OFF;
extern SemaphoreHandle_t xCtrlWinFlag_ON;
extern SemaphoreHandle_t xCtrlWinFlag_OFF;
extern SemaphoreHandle_t xCatchRecord;

Can_VMsg MV_Data;
Tim_TMsg MT_Data;

uint8_t Rec_Times=0;
uint8_t i;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Main_Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Record", ID_BUTTON_0, 320, 180, 100, 40, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "PAGE DN", ID_BUTTON_1, 320, 210, 100, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Ctrl Panel", ID_BUTTON_2, 320, 240, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
	case WM_PAINT:
		MWin_PaintDialog(pMsg);
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Main_Window'
    //
    hItem = pMsg->hWin;
//    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C53858));
    //
    // Initialization of 'Record'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Record");
    //
    // Initialization of 'PAGE DN'
    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
//    BUTTON_SetText(hItem, "PAGE DN");
//    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Ctrl Panel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "Ctrl Panel");
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'PAGE UP'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				xSemaphoreGive(xMaWinFlag_OFF);
				xSemaphoreGive(xRecWinFlag_ON);
				vTaskResume(Record_WinHandle);
        break;
      }
      break;

    case ID_BUTTON_2: // Notifications sent by 'Ctrl Panel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				xSemaphoreGive(xMaWinFlag_OFF);
				xSemaphoreGive(xCtrlWinFlag_ON);
				vTaskResume(Control_WinHandle);
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMain_Window
*/
void CreateMain_Window(void *pvParameters);
void CreateMain_Window(void *pvParameters) {
  WM_HWIN hWin;
	uint8_t MWin_Flag=1;
	
	WM_SetCreateFlags(WM_CF_MEMDEV);  						/* Use memory devices on all windows to avoid flicker */
	WM_SetDesktopColor(GUI_BLACK);      					/* Automacally update desktop window */
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	while(1)
	{	
		if(xSemaphoreTake(xMaWinFlag_OFF,0) == pdPASS)
		{
			if(MWin_Flag ==1)
			{
				MWin_Flag = 0;
				Init_TMsg(&MT_Data);
				GUI_EndDialog(WM_GetClientWindow(hWin), 1);
				vTaskSuspend(NULL);
			}
		}
		if(xSemaphoreTake(xMaWinFlag_ON,0) == pdPASS)
		{
			if(MWin_Flag ==0)
			{
				MWin_Flag = 1;
				hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
			}
		}
		if(uxQueueMessagesWaiting( xCAN_V_TxMessage ) != 0)
		{
			xQueueReceive( xCAN_V_TxMessage, &MV_Data, 0);
			printf("QueRecie CANTrans.\r\n");
			WM_InvalidateWindow(hWin);
		}
		if(uxQueueMessagesWaiting( xTIM_T_TxMessage ) != 0)
		{
			xQueueReceive( xTIM_T_TxMessage, &MT_Data, 0);
			WM_InvalidateWindow(hWin);
		}
		GUI_Delay(1);
	}
}
// USER START (Optionally insert additional public code)
void MWin_PaintDialog(WM_MESSAGE * pMsg)
{
	GUI_DrawGradientV(0,0,480,320,GUI_MAKE_COLOR(0x00C53858),GUI_DARKGREEN);
	GUI_DrawGradientRoundedV(260,15,460,75,7,GUI_DARKGRAY,GUI_BLACK);     //the rect. for distance and time
	GUI_DrawGradientRoundedV(260,85,460,145,7,GUI_DARKGRAY,GUI_BLACK);
	
	GUI_SetFont(GUI_FONT_32B_ASCII);								//speed table
	GUI_SetColor(GUI_ORANGE);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_DispStringAt("Velocity (km/h):",35,20);
	
	GUI_SetColor(GUI_WHITE);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(GUI_FONT_D48X64);
  GUI_GotoXY(35,80);
  GUI_DispFloatFix (MV_Data.V,4,1);      					 //display the speed
	
	GUI_SetFont(GUI_FONT_32B_1);
	GUI_DispDecAt(MT_Data.min, 265, 42, 2);
	GUI_DispDecAt(MT_Data.sec, 305, 42, 2);
	GUI_DispStringAt(":",295,42);                    //Display current time consumed
  GUI_GotoXY(265,112);
	GUI_DispFloatFix (MV_Data.distance,7,1);         //display the value of distance
	GUI_DispStringAt("m",380,112);
	
	GUI_SetFont(GUI_FONT_24B_ASCII);	
	GUI_SetColor(GUI_ORANGE);
	GUI_DispStringAt("Distance",265,88);
	GUI_DispStringAt("Stopwatch",265,18);
	GUI_DispStringAt("Record Column",35,148);

	GUI_SetFont(GUI_FONT_24B_ASCII);
	GUI_SetColor(GUI_ORANGE);
	GUI_DispStringAt("Max    :",35,210);
	GUI_DispStringAt("Min     :",35,240);
	GUI_DispStringAt("Times :",35,270);
	GUI_DispStringAt("Aver   :",35,180);
	GUI_SetColor(GUI_YELLOW);
	GUI_GotoXY(140,210);
	GUI_DispFloatFix (MV_Data.V_Max,4,1);
	GUI_GotoXY(140,240);
	GUI_DispFloatFix (MV_Data.V_Min,4,1);
	GUI_GotoXY(140,180);
	GUI_DispFloatFix (MV_Data.V_aver,4,1); 
	GUI_GotoXY(140,270);
	GUI_DispFloatFix (MV_Data.tick,4,1);  
}
// USER END
/*************************** End of file ****************************/
