/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Record_Window.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         	(GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_0         	(GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
extern SemaphoreHandle_t xAskRecord;

extern SemaphoreHandle_t xMaWinFlag_ON;
extern SemaphoreHandle_t xMaWinFlag_OFF;
extern SemaphoreHandle_t xRecWinFlag_ON;
extern SemaphoreHandle_t xRecWinFlag_OFF;

extern QueueHandle_t xCAN_V_TxMessage;
extern QueueHandle_t xTIM_T_TxMessage;
extern QueueHandle_t xCAN_V_RecordMessage;

extern TaskHandle_t Main_WinHandle;

Can_VMsg SV_Data;
Tim_TMsg ST_Data;
Can_VRecord Rec_Data[60];
uint8_t Rec_Receive=0,k;
double VminTime, VmaxTime;
const char *Text[5];
// USER END
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Record_Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 80, 480, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 320, 20, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
void RWin_PaintDialog(WM_MESSAGE * pMsg)
{
	WM_HWIN hWin = pMsg->hWin;
	hWin = hWin; //Useless, only to reference 'hWin'
	GUI_DrawGradientV(0,0,480,320,GUI_MAKE_COLOR(0x00C53858),GUI_DARKGREEN);
	GUI_SetColor(GUI_ORANGE);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(&GUI_Font32B_1);
	GUI_DispStringAt("Record History",15,25);
	GUI_DispDecAt(ST_Data.sec, 265, 25, 2);
	GUI_DispDecAt(ST_Data.min, 225, 25, 2);
	GUI_DispStringAt(":",255,25);
}
// USER END
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
	case WM_PAINT:
		RWin_PaintDialog(pMsg);
		break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Record_Window'
    //
    hItem = pMsg->hWin;
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		LISTVIEW_SetBkColor(WM_GetDialogItem(hItem,GUI_ID_LISTVIEW0),0,GUI_LIGHTGREEN);
		LISTVIEW_SetFont(WM_GetDialogItem(hItem,GUI_ID_LISTVIEW0),&GUI_Font24B_1);
    LISTVIEW_AddColumn(hItem, 96, "Times", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 96, "Vmax", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 96, "Vmin", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 96, "Acceleration", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 96, "Sliding", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 0);
    LISTVIEW_SetAutoScrollV(hItem, 1);
    LISTVIEW_SetRowHeight(hItem, 20);
    LISTVIEW_SetHeaderHeight(hItem, 25);
    LISTVIEW_SetFont(hItem, GUI_FONT_16B_ASCII);
		LISTVIEW_SetDefaultFont(GUI_FONT_20_ASCII);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Return");
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        break;
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				xSemaphoreGive(xMaWinFlag_ON);
//				vPrintString("xSemaphoreGive xMaWinFlag_ON\r\n");
				xSemaphoreGive(xRecWinFlag_OFF); 
//				vPrintString("xSemaphoreGive xRecWinFlag_OFF\r\n");
				vTaskResume(Main_WinHandle);
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateRecord_Window
*/
void Record_Window(void *pvParameters);
void Record_Window(void *pvParameters)
{
  WM_HWIN hWin,hItem;
	uint8_t RecWin_Flag=0;
	
	WM_SetCreateFlags(WM_CF_MEMDEV);  						/* Use memory devices on all windows to avoid flicker */
	WM_SetDesktopColor(GUI_BLACK);      /* Automacally update desktop window */

	Init_VMsg(&SV_Data);
	Init_TMsg(&ST_Data);
	
  while(1)
	{	
		if(xSemaphoreTake(xRecWinFlag_OFF,0) == pdPASS)
		{
			if(RecWin_Flag ==1)
			{
				Init_TMsg(&ST_Data);
				RecWin_Flag = 0;
				Rec_Receive=0;
				GUI_EndDialog(WM_GetClientWindow(hWin), 0);
				vTaskSuspend(NULL);
			}
		}
		GUI_Delay(1);
		if(xSemaphoreTake(xRecWinFlag_ON,0) == pdPASS)
		{
			if(RecWin_Flag ==0)
			{
				xSemaphoreGive(xAskRecord);
				hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
				RecWin_Flag = 1;
			}
		}
		if(uxQueueMessagesWaiting( xTIM_T_TxMessage ) != 0)
		{
			xQueueReceive( xTIM_T_TxMessage, &ST_Data, 0);
			WM_InvalidateWindow(hWin);
		}
		GUI_Delay(1);
		if(uxQueueMessagesWaiting( xCAN_V_RecordMessage ) != 0)
		{
			while(uxQueueMessagesWaiting( xCAN_V_RecordMessage ) != 0)
			{
				xQueueReceive( xCAN_V_RecordMessage, &Rec_Data[Rec_Receive], 0);
				Rec_Receive++;
			}
			for(k=0;k<Rec_Receive;)
			{	
				Text[0]=OrdNumConvert(k+1);
				Text[1]=NumConvert(Rec_Data[k].V_Max);
				Text[2]=NumConvert(Rec_Data[k].V_Min);
				
				if(k!=0){
					VminTime=Rec_Data[k-1].VminTime;
					VmaxTime=Rec_Data[k].VmaxTime;
					Text[3]=NumConvert(VmaxTime-VminTime);
				}
			  else
					Text[3]=NumConvert(VmaxTime);
				VmaxTime=(Rec_Data[k].VmaxTime);
				VminTime=(Rec_Data[k].VminTime);
				Text[4]=NumConvert(VminTime-VmaxTime);
				
				hItem = WM_GetDialogItem(hWin, ID_LISTVIEW_0);
				LISTVIEW_AddRow(hItem, Text);											//Ìí¼Ó1ÐÐ
				k++;
			}
		}
		GUI_Delay(1);
	}
}
// USER START (Optionally insert additional public code)
// USER END
/*************************** End of file ****************************/
